using XGArcade.Data.Entities;
using XGArcade.Data.Repositories;

namespace XGArcade.Core.Social;

// COMP-16 (Core.Social)/ADR-0103, S-210: REQ-1402's send/accept/decline
// implementation. Depends on IFriendRepository (REQ-1401) the same way it
// depends on IChallengeRepository — both are Core.Social's own persistence
// primitives, not a cross-component dependency (ADR-0003 doesn't apply
// between two entities owned by the same component).
public class ChallengeService(
    IChallengeRepository challengeRepository,
    IFriendRepository friendRepository,
    TimeProvider timeProvider) : IChallengeService
{
    public async Task<SendChallengeResult> SendChallengeAsync(
        Guid challengerUserId, Guid challengedUserId, CancellationToken cancellationToken = default)
    {
        // REQ-1402: "a direct challenge can only be sent to an existing
        // friend" — this single check also naturally rejects a self-
        // challenge and a challenge to a nonexistent user, since neither
        // can ever satisfy AreFriendsAsync (REQ-1401 never allows a user to
        // become friends with themselves, and a nonexistent recipient can
        // never have a Friendship row either).
        if (!await friendRepository.AreFriendsAsync(challengerUserId, challengedUserId, cancellationToken))
            return new SendChallengeResult(SendChallengeOutcome.NotFriends, null);

        // REQ-1402: "no second, duplicate pending challenge may exist from
        // User A to User B while the first is still pending" — checked in
        // both directions, same shape as FriendService.SendFriendRequestAsync's
        // own duplicate-pending check.
        var pendingForChallenged = await challengeRepository.GetPendingChallengesForUserAsync(challengedUserId, cancellationToken);
        if (pendingForChallenged.Any(c => c.ChallengerUserId == challengerUserId))
            return new SendChallengeResult(SendChallengeOutcome.DuplicatePending, null);

        var pendingForChallenger = await challengeRepository.GetPendingChallengesForUserAsync(challengerUserId, cancellationToken);
        if (pendingForChallenger.Any(c => c.ChallengerUserId == challengedUserId))
            return new SendChallengeResult(SendChallengeOutcome.DuplicatePending, null);

        var challenge = new Challenge
        {
            Id = Guid.NewGuid(),
            ChallengerUserId = challengerUserId,
            ChallengedUserId = challengedUserId,
            Status = ChallengeStatus.Pending,
            CreatedAt = timeProvider.GetUtcNow().UtcDateTime,
        };

        var created = await challengeRepository.AddChallengeAsync(challenge, cancellationToken);
        return new SendChallengeResult(SendChallengeOutcome.Sent, created);
    }

    public async Task<ResolveChallengeResult> AcceptChallengeAsync(
        Guid challengeId, Guid respondingUserId, Guid resultingMatchId, CancellationToken cancellationToken = default)
    {
        var (failureOutcome, challenge) = await ValidateResolvableAsync(challengeId, respondingUserId, cancellationToken);
        if (failureOutcome is not null)
            return new ResolveChallengeResult(failureOutcome.Value, null);

        var resolvedAt = timeProvider.GetUtcNow().UtcDateTime;

        // resultingMatchId is pre-generated by the XGArcade.Api caller,
        // which creates the actual ConnectMatch row itself immediately
        // after this call returns Resolved — see IChallengeService's own
        // doc comment for why that write never happens inside Core.Social.
        await challengeRepository.UpdateChallengeStatusAsync(
            challengeId, ChallengeStatus.Accepted, resolvedAt, resultingMatchId, cancellationToken);

        challenge!.Status = ChallengeStatus.Accepted;
        challenge.ResolvedAt = resolvedAt;
        challenge.ResultingMatchId = resultingMatchId;

        return new ResolveChallengeResult(ResolveChallengeOutcome.Resolved, challenge);
    }

    public async Task<ResolveChallengeResult> DeclineChallengeAsync(
        Guid challengeId, Guid respondingUserId, CancellationToken cancellationToken = default)
    {
        var (failureOutcome, challenge) = await ValidateResolvableAsync(challengeId, respondingUserId, cancellationToken);
        if (failureOutcome is not null)
            return new ResolveChallengeResult(failureOutcome.Value, null);

        var resolvedAt = timeProvider.GetUtcNow().UtcDateTime;

        await challengeRepository.UpdateChallengeStatusAsync(
            challengeId, ChallengeStatus.Declined, resolvedAt, resultingMatchId: null, cancellationToken);

        challenge!.Status = ChallengeStatus.Declined;
        challenge.ResolvedAt = resolvedAt;

        return new ResolveChallengeResult(ResolveChallengeOutcome.Resolved, challenge);
    }

    public Task<IReadOnlyList<Challenge>> GetPendingChallengesAsync(
        Guid userId, CancellationToken cancellationToken = default) =>
        challengeRepository.GetPendingChallengesForUserAsync(userId, cancellationToken);

    // Accept/decline share every precondition check (found, responder is
    // the challenged user, still Pending) but differ in which final Status
    // is written and whether a resultingMatchId is ever supplied — unlike
    // FriendService's own accept/decline (a single accept: bool flag flips
    // one extra step, creating a Friendship), AcceptChallengeAsync also
    // needs a caller-supplied Guid that DeclineChallengeAsync has no use
    // for, so a full single-method merge would need an awkward "is null
    // matchId a real decline, or just an accept caller who forgot it"
    // ambiguity. Factoring only the shared validation avoids that.
    private async Task<(ResolveChallengeOutcome? FailureOutcome, Challenge? Challenge)> ValidateResolvableAsync(
        Guid challengeId, Guid respondingUserId, CancellationToken cancellationToken)
    {
        var challenge = await challengeRepository.GetChallengeByIdAsync(challengeId, cancellationToken);
        if (challenge is null)
            return (ResolveChallengeOutcome.NotFound, null);

        // Only the challenged user may accept/decline — never the
        // challenger, who could otherwise auto-resolve their own outgoing
        // challenge.
        if (challenge.ChallengedUserId != respondingUserId)
            return (ResolveChallengeOutcome.NotYourChallenge, null);

        if (challenge.Status != ChallengeStatus.Pending)
            return (ResolveChallengeOutcome.AlreadyResolved, null);

        return (null, challenge);
    }
}
