using XGArcade.Data.Entities;

namespace XGArcade.Core.Social;

// COMP-16 (Core.Social)/ADR-0103, S-210: REQ-1402's send/accept/decline
// business logic, layered on top of IChallengeRepository's pure
// persistence primitives (S-208) — same "outcome enum + result record for
// expected branches" shape as IFriendService, and the friendship
// precondition itself is checked here (via IFriendRepository.
// AreFriendsAsync) rather than in the repository, mirroring how
// IFriendService's own duplicate-pending/already-friends checks live in
// FriendService, not FriendRepository.
//
// Deliberately does NOT create the resulting ConnectMatch row itself —
// ADR-0103 requires Core.Social to never take a compile-time dependency on
// Games.XGConnect/IConnectMatchRepository. AcceptChallengeAsync takes a
// caller-supplied resultingMatchId (pre-generated by the XGArcade.Api
// orchestration step that also creates the ConnectMatch row) so the
// Accepted status and ResultingMatchId can be persisted in the exact same
// call that validates every accept precondition — see
// XGArcade.Api.Social.ChallengeEndpoints' accept handler for the other
// half of this orchestration.
public interface IChallengeService
{
    // REQ-1402: creates a Pending Challenge from challengerUserId to
    // challengedUserId. Rejects (without ever calling
    // IChallengeRepository.AddChallengeAsync) when: the two users are not
    // friends (NotFriends — this is also what a self-challenge or a
    // challenge to a nonexistent user naturally falls into, since neither
    // can ever be a friend per REQ-1401's own self-request rejection), or a
    // Pending challenge already exists between them in either direction
    // (DuplicatePending).
    Task<SendChallengeResult> SendChallengeAsync(
        Guid challengerUserId, Guid challengedUserId, CancellationToken cancellationToken = default);

    // REQ-1402: resolves a Pending Challenge as Accepted and persists
    // resultingMatchId in the same call — the caller (XGArcade.Api) has
    // already pre-generated that id and creates the actual ConnectMatch row
    // itself, immediately after this call returns Resolved (never before —
    // an invalid accept attempt must never leave an orphan ConnectMatch
    // nobody points to). Only the challenge's ChallengedUserId may accept it.
    Task<ResolveChallengeResult> AcceptChallengeAsync(
        Guid challengeId, Guid respondingUserId, Guid resultingMatchId, CancellationToken cancellationToken = default);

    // REQ-1402: resolves a Pending Challenge as Declined — no match is ever
    // created, and (since only the challenge row's Status changes) the same
    // challenger is free to send a new challenge later.
    Task<ResolveChallengeResult> DeclineChallengeAsync(
        Guid challengeId, Guid respondingUserId, CancellationToken cancellationToken = default);

    // REQ-1402: every Pending challenge where userId is the challenged
    // party — lets a player see who's challenged them.
    Task<IReadOnlyList<Challenge>> GetPendingChallengesAsync(
        Guid userId, CancellationToken cancellationToken = default);
}

public enum SendChallengeOutcome
{
    Sent,
    NotFriends,
    DuplicatePending,
}

// Challenge is non-null only when Outcome is Sent.
public record SendChallengeResult(SendChallengeOutcome Outcome, Challenge? Challenge);

public enum ResolveChallengeOutcome
{
    Resolved,
    NotFound,
    NotYourChallenge,
    AlreadyResolved,
}

// Challenge is non-null only when Outcome is Resolved.
public record ResolveChallengeResult(ResolveChallengeOutcome Outcome, Challenge? Challenge);
