// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XGArcade.Data;

#nullable disable

namespace XGArcade.Data.Migrations
{
    [DbContext(typeof(XGArcadeDbContext))]
    [Migration("20260830120000_AddPredictInstance")]
    partial class AddPredictInstance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XGArcade.Data.Entities.AnnouncementBanner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastUpdatedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AnnouncementBanners");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.AvatarSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageStorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmittingUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmittingUserId", "Status");

                    b.ToTable("AvatarSubmissions");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.ClubDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PlayerPoolSweptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WikidataQid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ClubDefinitions");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.ConfirmedLowMatchPair", b =>
                {
                    b.Property<string>("FirstAttributeType")
                        .HasColumnType("text");

                    b.Property<string>("FirstAttributeValue")
                        .HasColumnType("text");

                    b.Property<string>("SecondAttributeType")
                        .HasColumnType("text");

                    b.Property<string>("SecondAttributeValue")
                        .HasColumnType("text");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchCount")
                        .HasColumnType("integer");

                    b.HasKey("FirstAttributeType", "FirstAttributeValue", "SecondAttributeType", "SecondAttributeValue");

                    b.HasIndex("SecondAttributeType", "SecondAttributeValue");

                    b.ToTable("ConfirmedLowMatchPairs");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.CountryDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PlayerPoolSweptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UsesCountryForSportProperty")
                        .HasColumnType("boolean");

                    b.Property<string>("WikidataQid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CountryDefinitions");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.GridCell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Col")
                        .HasColumnType("integer");

                    b.Property<string>("ColCategoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColCategoryValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GridInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<string>("RowCategoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RowCategoryValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GridInstanceId", "Row", "Col")
                        .IsUnique();

                    b.ToTable("GridCells");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.GridInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("GridInstances");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.GridTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("AllowedCategoryTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GridTemplates");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.Guess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("CellId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FinalPoints")
                        .HasColumnType("integer");

                    b.Property<double?>("FinalUniquenessScore")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("MatchedPlayerName")
                        .HasColumnType("text");

                    b.Property<string>("MatchedPlayerPhotoUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("PlayerAnswerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubmittedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CellId");

                    b.HasIndex("RoundId", "UserId", "CellId")
                        .IsUnique();

                    b.ToTable("Guesses");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("InviteCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("Type")
                        .IsUnique()
                        .HasFilter("\"Type\" = 'global'");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.LeagueMembership", b =>
                {
                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LeagueId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("LeagueMemberships");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PairLookupFailure", b =>
                {
                    b.Property<string>("FirstAttributeType")
                        .HasColumnType("text");

                    b.Property<string>("FirstAttributeValue")
                        .HasColumnType("text");

                    b.Property<string>("SecondAttributeType")
                        .HasColumnType("text");

                    b.Property<string>("SecondAttributeValue")
                        .HasColumnType("text");

                    b.Property<int>("ConsecutiveFailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastFailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FirstAttributeType", "FirstAttributeValue", "SecondAttributeType", "SecondAttributeValue");

                    b.HasIndex("SecondAttributeType", "SecondAttributeValue");

                    b.ToTable("PairLookupFailures");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PathCycleTargetUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CycleNumber");

                    b.HasIndex("PlayerId", "CycleNumber")
                        .IsUnique();

                    b.ToTable("PathCycleTargetUsages");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PathInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PathInstances");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PathPuzzle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PathInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetPlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetPlayerId");

                    b.HasIndex("PathInstanceId", "TargetPlayerId")
                        .IsUnique();

                    b.ToTable("PathPuzzles");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PathTargetCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastCycleCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ObservedPoolSize")
                        .HasColumnType("integer");

                    b.Property<int>("UsedInCycleCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PathTargetCycles");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PathTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("PuzzleCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PathTemplates");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("WikidataQid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedFullName");

                    b.HasIndex("WikidataQid")
                        .IsUnique()
                        .HasFilter("\"WikidataQid\" IS NOT NULL");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerAlias", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedAlias")
                        .HasColumnType("text");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlayerId", "NormalizedAlias");

                    b.ToTable("PlayerAliases");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerAttribute", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeType")
                        .HasColumnType("text");

                    b.Property<string>("AttributeValue")
                        .HasColumnType("text");

                    b.HasKey("PlayerId", "AttributeType", "AttributeValue");

                    b.HasIndex("AttributeType", "AttributeValue");

                    b.ToTable("PlayerAttributes");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerCareerStint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AppearanceCount")
                        .HasColumnType("integer");

                    b.Property<string>("ClubName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCareerStints");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerData");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerNameIndex", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryNationality")
                        .HasColumnType("text");

                    b.HasKey("PlayerId");

                    b.HasIndex("NormalizedName");

                    b.ToTable("PlayerNameIndexEntries");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerNameIndexWord", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Word")
                        .HasColumnType("text");

                    b.HasKey("PlayerId", "Word");

                    b.HasIndex("Word");

                    b.ToTable("PlayerNameIndexWords");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LockedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerOverrides");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssertedNationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CellId")
                        .HasColumnType("uuid");

                    b.Property<string>("ColCategoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<string>("RowCategoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmittingUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.HasIndex("Status");

                    b.ToTable("PlayerSuggestions");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerSuggestionClub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClubName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerSuggestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerSuggestionId");

                    b.ToTable("PlayerSuggestionClubs");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PredictInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PredictInstances");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PredictMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExternalFixtureId")
                        .HasColumnType("integer");

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("KickoffUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PredictInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PredictInstanceId");

                    b.ToTable("PredictMatches");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PredictMatchPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("integer");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("integer");

                    b.Property<Guid>("PredictMatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PredictMatchId", "UserId")
                        .IsUnique();

                    b.ToTable("PredictMatchPredictions");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PredictTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MatchCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PredictTemplates");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowGuessChange")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("GameKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameKey", "EndTime");

                    b.HasIndex("GameKey", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.TrophyDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsTeamTrophy")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WikidataQid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TrophyDefinitions");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthProviderUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthProviderUserId")
                        .IsUnique();

                    b.HasIndex("NormalizedDisplayName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.GridCell", b =>
                {
                    b.HasOne("XGArcade.Data.Entities.GridInstance", null)
                        .WithMany("Cells")
                        .HasForeignKey("GridInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XGArcade.Data.Entities.Guess", b =>
                {
                    b.HasOne("XGArcade.Data.Entities.Round", null)
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XGArcade.Data.Entities.LeagueMembership", b =>
                {
                    b.HasOne("XGArcade.Data.Entities.League", null)
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XGArcade.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PathCycleTargetUsage", b =>
                {
                    b.HasOne("XGArcade.Data.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PathPuzzle", b =>
                {
                    b.HasOne("XGArcade.Data.Entities.PathInstance", null)
                        .WithMany("Puzzles")
                        .HasForeignKey("PathInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XGArcade.Data.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("TargetPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerAlias", b =>
                {
                    b.HasOne("XGArcade.Data.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerAttribute", b =>
                {
                    b.HasOne("XGArcade.Data.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerCareerStint", b =>
                {
                    b.HasOne("XGArcade.Data.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerData", b =>
                {
                    b.HasOne("XGArcade.Data.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerNameIndexWord", b =>
                {
                    b.HasOne("XGArcade.Data.Entities.PlayerNameIndex", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerOverride", b =>
                {
                    b.HasOne("XGArcade.Data.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerSuggestion", b =>
                {
                    b.HasOne("XGArcade.Data.Entities.Round", null)
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerSuggestionClub", b =>
                {
                    b.HasOne("XGArcade.Data.Entities.PlayerSuggestion", null)
                        .WithMany("AssertedClubs")
                        .HasForeignKey("PlayerSuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PredictMatch", b =>
                {
                    b.HasOne("XGArcade.Data.Entities.PredictInstance", null)
                        .WithMany("Matches")
                        .HasForeignKey("PredictInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PredictMatchPrediction", b =>
                {
                    b.HasOne("XGArcade.Data.Entities.PredictMatch", null)
                        .WithMany()
                        .HasForeignKey("PredictMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XGArcade.Data.Entities.GridInstance", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PathInstance", b =>
                {
                    b.Navigation("Puzzles");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PlayerSuggestion", b =>
                {
                    b.Navigation("AssertedClubs");
                });

            modelBuilder.Entity("XGArcade.Data.Entities.PredictInstance", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
